/*
accent-calld

Control your calls from a REST API

API version: 1.0.0
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package calld

import (
	"encoding/json"
)

// checks if the Application type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Application{}

// Application struct for Application
type Application struct {
	DestinationNodeUuid *string `json:"destination_node_uuid,omitempty"`
}

// NewApplication instantiates a new Application object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplication() *Application {
	this := Application{}
	return &this
}

// NewApplicationWithDefaults instantiates a new Application object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationWithDefaults() *Application {
	this := Application{}
	return &this
}

// GetDestinationNodeUuid returns the DestinationNodeUuid field value if set, zero value otherwise.
func (o *Application) GetDestinationNodeUuid() string {
	if o == nil || IsNil(o.DestinationNodeUuid) {
		var ret string
		return ret
	}
	return *o.DestinationNodeUuid
}

// GetDestinationNodeUuidOk returns a tuple with the DestinationNodeUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Application) GetDestinationNodeUuidOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationNodeUuid) {
		return nil, false
	}
	return o.DestinationNodeUuid, true
}

// HasDestinationNodeUuid returns a boolean if a field has been set.
func (o *Application) HasDestinationNodeUuid() bool {
	if o != nil && !IsNil(o.DestinationNodeUuid) {
		return true
	}

	return false
}

// SetDestinationNodeUuid gets a reference to the given string and assigns it to the DestinationNodeUuid field.
func (o *Application) SetDestinationNodeUuid(v string) {
	o.DestinationNodeUuid = &v
}

func (o Application) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Application) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DestinationNodeUuid) {
		toSerialize["destination_node_uuid"] = o.DestinationNodeUuid
	}
	return toSerialize, nil
}

type NullableApplication struct {
	value *Application
	isSet bool
}

func (v NullableApplication) Get() *Application {
	return v.value
}

func (v *NullableApplication) Set(val *Application) {
	v.value = val
	v.isSet = true
}

func (v NullableApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplication(val *Application) *NullableApplication {
	return &NullableApplication{value: val, isSet: true}
}

func (v NullableApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
