/*
accent-calld

Control your calls from a REST API

API version: 1.0.0
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package calld

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TransferRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferRequest{}

// TransferRequest struct for TransferRequest
type TransferRequest struct {
	// Context of the recipient of the transfer
	Context string `json:"context"`
	// Extension of the recipient of the transfer
	Exten string        `json:"exten"`
	Flow  *TransferFlow `json:"flow,omitempty"`
	// Call ID of the transfer initiator
	InitiatorCall string `json:"initiator_call"`
	// Maximum ringing time before cancelling the transfer (in seconds). Default (or null) is an unlimited ring time.
	Timeout *int32 `json:"timeout,omitempty"`
	// Call ID of the call being transferred to someone else
	TransferredCall string `json:"transferred_call"`
	// Channel variables to set on the recipient call
	Variables map[string]interface{} `json:"variables,omitempty"`
}

type _TransferRequest TransferRequest

// NewTransferRequest instantiates a new TransferRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferRequest(context string, exten string, initiatorCall string, transferredCall string) *TransferRequest {
	this := TransferRequest{}
	this.Context = context
	this.Exten = exten
	var flow TransferFlow = TRANSFERFLOW_ATTENDED
	this.Flow = &flow
	this.InitiatorCall = initiatorCall
	this.TransferredCall = transferredCall
	return &this
}

// NewTransferRequestWithDefaults instantiates a new TransferRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferRequestWithDefaults() *TransferRequest {
	this := TransferRequest{}
	var flow TransferFlow = TRANSFERFLOW_ATTENDED
	this.Flow = &flow
	return &this
}

// GetContext returns the Context field value
func (o *TransferRequest) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *TransferRequest) SetContext(v string) {
	o.Context = v
}

// GetExten returns the Exten field value
func (o *TransferRequest) GetExten() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Exten
}

// GetExtenOk returns a tuple with the Exten field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetExtenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exten, true
}

// SetExten sets field value
func (o *TransferRequest) SetExten(v string) {
	o.Exten = v
}

// GetFlow returns the Flow field value if set, zero value otherwise.
func (o *TransferRequest) GetFlow() TransferFlow {
	if o == nil || IsNil(o.Flow) {
		var ret TransferFlow
		return ret
	}
	return *o.Flow
}

// GetFlowOk returns a tuple with the Flow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetFlowOk() (*TransferFlow, bool) {
	if o == nil || IsNil(o.Flow) {
		return nil, false
	}
	return o.Flow, true
}

// HasFlow returns a boolean if a field has been set.
func (o *TransferRequest) HasFlow() bool {
	if o != nil && !IsNil(o.Flow) {
		return true
	}

	return false
}

// SetFlow gets a reference to the given TransferFlow and assigns it to the Flow field.
func (o *TransferRequest) SetFlow(v TransferFlow) {
	o.Flow = &v
}

// GetInitiatorCall returns the InitiatorCall field value
func (o *TransferRequest) GetInitiatorCall() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InitiatorCall
}

// GetInitiatorCallOk returns a tuple with the InitiatorCall field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetInitiatorCallOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InitiatorCall, true
}

// SetInitiatorCall sets field value
func (o *TransferRequest) SetInitiatorCall(v string) {
	o.InitiatorCall = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *TransferRequest) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *TransferRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *TransferRequest) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetTransferredCall returns the TransferredCall field value
func (o *TransferRequest) GetTransferredCall() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransferredCall
}

// GetTransferredCallOk returns a tuple with the TransferredCall field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetTransferredCallOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransferredCall, true
}

// SetTransferredCall sets field value
func (o *TransferRequest) SetTransferredCall(v string) {
	o.TransferredCall = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *TransferRequest) GetVariables() map[string]interface{} {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]interface{}
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetVariablesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]interface{}{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *TransferRequest) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *TransferRequest) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

func (o TransferRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["exten"] = o.Exten
	if !IsNil(o.Flow) {
		toSerialize["flow"] = o.Flow
	}
	toSerialize["initiator_call"] = o.InitiatorCall
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	toSerialize["transferred_call"] = o.TransferredCall
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

func (o *TransferRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"context",
		"exten",
		"initiator_call",
		"transferred_call",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransferRequest := _TransferRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransferRequest)

	if err != nil {
		return err
	}

	*o = TransferRequest(varTransferRequest)

	return err
}

type NullableTransferRequest struct {
	value *TransferRequest
	isSet bool
}

func (v NullableTransferRequest) Get() *TransferRequest {
	return v.value
}

func (v *NullableTransferRequest) Set(val *TransferRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferRequest(val *TransferRequest) *NullableTransferRequest {
	return &NullableTransferRequest{value: val, isSet: true}
}

func (v NullableTransferRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
