/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CallFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallFilter{}

// CallFilter struct for CallFilter
type CallFilter struct {
	Recipients *CallFilterRecipientUsers `json:"recipients,omitempty"`
	Surrogates *CallFilterSurrogateUsers `json:"surrogates,omitempty"`
	// How the caller_id_name will be treated
	CallerIdMode *string `json:"caller_id_mode,omitempty"`
	// Name to display
	CallerIdName *string `json:"caller_id_name,omitempty"`
	// Additional information about the call filter
	Description *string `json:"description,omitempty"`
	// Disable or enable the call filter
	Enabled *bool `json:"enabled,omitempty"`
	// The id of the call filter
	Id *int32 `json:"id,omitempty"`
	// The name of the call filter
	Name string `json:"name"`
	// Call type to apply call filter
	Source string `json:"source"`
	// Determine which will ring.
	Strategy string `json:"strategy"`
	// Number of seconds the filter's surrogates will ring before falling back
	SurrogatesTimeout *int32 `json:"surrogates_timeout,omitempty"`
	// The UUID of the tenant
	TenantUuid *string `json:"tenant_uuid,omitempty"`
}

type _CallFilter CallFilter

// NewCallFilter instantiates a new CallFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallFilter(name string, source string, strategy string) *CallFilter {
	this := CallFilter{}
	var enabled bool = true
	this.Enabled = &enabled
	this.Name = name
	this.Source = source
	this.Strategy = strategy
	return &this
}

// NewCallFilterWithDefaults instantiates a new CallFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallFilterWithDefaults() *CallFilter {
	this := CallFilter{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetRecipients returns the Recipients field value if set, zero value otherwise.
func (o *CallFilter) GetRecipients() CallFilterRecipientUsers {
	if o == nil || IsNil(o.Recipients) {
		var ret CallFilterRecipientUsers
		return ret
	}
	return *o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetRecipientsOk() (*CallFilterRecipientUsers, bool) {
	if o == nil || IsNil(o.Recipients) {
		return nil, false
	}
	return o.Recipients, true
}

// HasRecipients returns a boolean if a field has been set.
func (o *CallFilter) HasRecipients() bool {
	if o != nil && !IsNil(o.Recipients) {
		return true
	}

	return false
}

// SetRecipients gets a reference to the given CallFilterRecipientUsers and assigns it to the Recipients field.
func (o *CallFilter) SetRecipients(v CallFilterRecipientUsers) {
	o.Recipients = &v
}

// GetSurrogates returns the Surrogates field value if set, zero value otherwise.
func (o *CallFilter) GetSurrogates() CallFilterSurrogateUsers {
	if o == nil || IsNil(o.Surrogates) {
		var ret CallFilterSurrogateUsers
		return ret
	}
	return *o.Surrogates
}

// GetSurrogatesOk returns a tuple with the Surrogates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetSurrogatesOk() (*CallFilterSurrogateUsers, bool) {
	if o == nil || IsNil(o.Surrogates) {
		return nil, false
	}
	return o.Surrogates, true
}

// HasSurrogates returns a boolean if a field has been set.
func (o *CallFilter) HasSurrogates() bool {
	if o != nil && !IsNil(o.Surrogates) {
		return true
	}

	return false
}

// SetSurrogates gets a reference to the given CallFilterSurrogateUsers and assigns it to the Surrogates field.
func (o *CallFilter) SetSurrogates(v CallFilterSurrogateUsers) {
	o.Surrogates = &v
}

// GetCallerIdMode returns the CallerIdMode field value if set, zero value otherwise.
func (o *CallFilter) GetCallerIdMode() string {
	if o == nil || IsNil(o.CallerIdMode) {
		var ret string
		return ret
	}
	return *o.CallerIdMode
}

// GetCallerIdModeOk returns a tuple with the CallerIdMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetCallerIdModeOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdMode) {
		return nil, false
	}
	return o.CallerIdMode, true
}

// HasCallerIdMode returns a boolean if a field has been set.
func (o *CallFilter) HasCallerIdMode() bool {
	if o != nil && !IsNil(o.CallerIdMode) {
		return true
	}

	return false
}

// SetCallerIdMode gets a reference to the given string and assigns it to the CallerIdMode field.
func (o *CallFilter) SetCallerIdMode(v string) {
	o.CallerIdMode = &v
}

// GetCallerIdName returns the CallerIdName field value if set, zero value otherwise.
func (o *CallFilter) GetCallerIdName() string {
	if o == nil || IsNil(o.CallerIdName) {
		var ret string
		return ret
	}
	return *o.CallerIdName
}

// GetCallerIdNameOk returns a tuple with the CallerIdName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetCallerIdNameOk() (*string, bool) {
	if o == nil || IsNil(o.CallerIdName) {
		return nil, false
	}
	return o.CallerIdName, true
}

// HasCallerIdName returns a boolean if a field has been set.
func (o *CallFilter) HasCallerIdName() bool {
	if o != nil && !IsNil(o.CallerIdName) {
		return true
	}

	return false
}

// SetCallerIdName gets a reference to the given string and assigns it to the CallerIdName field.
func (o *CallFilter) SetCallerIdName(v string) {
	o.CallerIdName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CallFilter) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CallFilter) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CallFilter) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CallFilter) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CallFilter) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CallFilter) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CallFilter) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CallFilter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CallFilter) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *CallFilter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CallFilter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CallFilter) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *CallFilter) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CallFilter) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CallFilter) SetSource(v string) {
	o.Source = v
}

// GetStrategy returns the Strategy field value
func (o *CallFilter) GetStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Strategy
}

// GetStrategyOk returns a tuple with the Strategy field value
// and a boolean to check if the value has been set.
func (o *CallFilter) GetStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Strategy, true
}

// SetStrategy sets field value
func (o *CallFilter) SetStrategy(v string) {
	o.Strategy = v
}

// GetSurrogatesTimeout returns the SurrogatesTimeout field value if set, zero value otherwise.
func (o *CallFilter) GetSurrogatesTimeout() int32 {
	if o == nil || IsNil(o.SurrogatesTimeout) {
		var ret int32
		return ret
	}
	return *o.SurrogatesTimeout
}

// GetSurrogatesTimeoutOk returns a tuple with the SurrogatesTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetSurrogatesTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.SurrogatesTimeout) {
		return nil, false
	}
	return o.SurrogatesTimeout, true
}

// HasSurrogatesTimeout returns a boolean if a field has been set.
func (o *CallFilter) HasSurrogatesTimeout() bool {
	if o != nil && !IsNil(o.SurrogatesTimeout) {
		return true
	}

	return false
}

// SetSurrogatesTimeout gets a reference to the given int32 and assigns it to the SurrogatesTimeout field.
func (o *CallFilter) SetSurrogatesTimeout(v int32) {
	o.SurrogatesTimeout = &v
}

// GetTenantUuid returns the TenantUuid field value if set, zero value otherwise.
func (o *CallFilter) GetTenantUuid() string {
	if o == nil || IsNil(o.TenantUuid) {
		var ret string
		return ret
	}
	return *o.TenantUuid
}

// GetTenantUuidOk returns a tuple with the TenantUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilter) GetTenantUuidOk() (*string, bool) {
	if o == nil || IsNil(o.TenantUuid) {
		return nil, false
	}
	return o.TenantUuid, true
}

// HasTenantUuid returns a boolean if a field has been set.
func (o *CallFilter) HasTenantUuid() bool {
	if o != nil && !IsNil(o.TenantUuid) {
		return true
	}

	return false
}

// SetTenantUuid gets a reference to the given string and assigns it to the TenantUuid field.
func (o *CallFilter) SetTenantUuid(v string) {
	o.TenantUuid = &v
}

func (o CallFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Recipients) {
		toSerialize["recipients"] = o.Recipients
	}
	if !IsNil(o.Surrogates) {
		toSerialize["surrogates"] = o.Surrogates
	}
	if !IsNil(o.CallerIdMode) {
		toSerialize["caller_id_mode"] = o.CallerIdMode
	}
	if !IsNil(o.CallerIdName) {
		toSerialize["caller_id_name"] = o.CallerIdName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source
	toSerialize["strategy"] = o.Strategy
	if !IsNil(o.SurrogatesTimeout) {
		toSerialize["surrogates_timeout"] = o.SurrogatesTimeout
	}
	if !IsNil(o.TenantUuid) {
		toSerialize["tenant_uuid"] = o.TenantUuid
	}
	return toSerialize, nil
}

func (o *CallFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"source",
		"strategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCallFilter := _CallFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCallFilter)

	if err != nil {
		return err
	}

	*o = CallFilter(varCallFilter)

	return err
}

type NullableCallFilter struct {
	value *CallFilter
	isSet bool
}

func (v NullableCallFilter) Get() *CallFilter {
	return v.value
}

func (v *NullableCallFilter) Set(val *CallFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableCallFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableCallFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallFilter(val *CallFilter) *NullableCallFilter {
	return &NullableCallFilter{value: val, isSet: true}
}

func (v NullableCallFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
