/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the AgentRelationQueue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRelationQueue{}

// AgentRelationQueue struct for AgentRelationQueue
type AgentRelationQueue struct {
	// The id of the queue
	Id *int32 `json:"id,omitempty"`
	// The label of the queue
	Label *string `json:"label,omitempty"`
	// The name of the queue. Cannot be modified
	Name *string `json:"name,omitempty"`
	// Agent's penalty. A priority used for distributing calls.
	Penalty *int32 `json:"penalty,omitempty"`
}

// NewAgentRelationQueue instantiates a new AgentRelationQueue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRelationQueue() *AgentRelationQueue {
	this := AgentRelationQueue{}
	return &this
}

// NewAgentRelationQueueWithDefaults instantiates a new AgentRelationQueue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentRelationQueueWithDefaults() *AgentRelationQueue {
	this := AgentRelationQueue{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentRelationQueue) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelationQueue) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentRelationQueue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AgentRelationQueue) SetId(v int32) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *AgentRelationQueue) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelationQueue) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *AgentRelationQueue) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *AgentRelationQueue) SetLabel(v string) {
	o.Label = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentRelationQueue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelationQueue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentRelationQueue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentRelationQueue) SetName(v string) {
	o.Name = &v
}

// GetPenalty returns the Penalty field value if set, zero value otherwise.
func (o *AgentRelationQueue) GetPenalty() int32 {
	if o == nil || IsNil(o.Penalty) {
		var ret int32
		return ret
	}
	return *o.Penalty
}

// GetPenaltyOk returns a tuple with the Penalty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelationQueue) GetPenaltyOk() (*int32, bool) {
	if o == nil || IsNil(o.Penalty) {
		return nil, false
	}
	return o.Penalty, true
}

// HasPenalty returns a boolean if a field has been set.
func (o *AgentRelationQueue) HasPenalty() bool {
	if o != nil && !IsNil(o.Penalty) {
		return true
	}

	return false
}

// SetPenalty gets a reference to the given int32 and assigns it to the Penalty field.
func (o *AgentRelationQueue) SetPenalty(v int32) {
	o.Penalty = &v
}

func (o AgentRelationQueue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRelationQueue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Penalty) {
		toSerialize["penalty"] = o.Penalty
	}
	return toSerialize, nil
}

type NullableAgentRelationQueue struct {
	value *AgentRelationQueue
	isSet bool
}

func (v NullableAgentRelationQueue) Get() *AgentRelationQueue {
	return v.value
}

func (v *NullableAgentRelationQueue) Set(val *AgentRelationQueue) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRelationQueue) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRelationQueue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRelationQueue(val *AgentRelationQueue) *NullableAgentRelationQueue {
	return &NullableAgentRelationQueue{value: val, isSet: true}
}

func (v NullableAgentRelationQueue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRelationQueue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
