/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the CallFilterSurrogates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallFilterSurrogates{}

// CallFilterSurrogates struct for CallFilterSurrogates
type CallFilterSurrogates struct {
	Surrogates *CallFilterSurrogateUsers `json:"surrogates,omitempty"`
}

// NewCallFilterSurrogates instantiates a new CallFilterSurrogates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallFilterSurrogates() *CallFilterSurrogates {
	this := CallFilterSurrogates{}
	return &this
}

// NewCallFilterSurrogatesWithDefaults instantiates a new CallFilterSurrogates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallFilterSurrogatesWithDefaults() *CallFilterSurrogates {
	this := CallFilterSurrogates{}
	return &this
}

// GetSurrogates returns the Surrogates field value if set, zero value otherwise.
func (o *CallFilterSurrogates) GetSurrogates() CallFilterSurrogateUsers {
	if o == nil || IsNil(o.Surrogates) {
		var ret CallFilterSurrogateUsers
		return ret
	}
	return *o.Surrogates
}

// GetSurrogatesOk returns a tuple with the Surrogates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallFilterSurrogates) GetSurrogatesOk() (*CallFilterSurrogateUsers, bool) {
	if o == nil || IsNil(o.Surrogates) {
		return nil, false
	}
	return o.Surrogates, true
}

// HasSurrogates returns a boolean if a field has been set.
func (o *CallFilterSurrogates) HasSurrogates() bool {
	if o != nil && !IsNil(o.Surrogates) {
		return true
	}

	return false
}

// SetSurrogates gets a reference to the given CallFilterSurrogateUsers and assigns it to the Surrogates field.
func (o *CallFilterSurrogates) SetSurrogates(v CallFilterSurrogateUsers) {
	o.Surrogates = &v
}

func (o CallFilterSurrogates) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallFilterSurrogates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Surrogates) {
		toSerialize["surrogates"] = o.Surrogates
	}
	return toSerialize, nil
}

type NullableCallFilterSurrogates struct {
	value *CallFilterSurrogates
	isSet bool
}

func (v NullableCallFilterSurrogates) Get() *CallFilterSurrogates {
	return v.value
}

func (v *NullableCallFilterSurrogates) Set(val *CallFilterSurrogates) {
	v.value = val
	v.isSet = true
}

func (v NullableCallFilterSurrogates) IsSet() bool {
	return v.isSet
}

func (v *NullableCallFilterSurrogates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallFilterSurrogates(val *CallFilterSurrogates) *NullableCallFilterSurrogates {
	return &NullableCallFilterSurrogates{value: val, isSet: true}
}

func (v NullableCallFilterSurrogates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallFilterSurrogates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
