/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the GroupRelationCallPermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupRelationCallPermissions{}

// GroupRelationCallPermissions struct for GroupRelationCallPermissions
type GroupRelationCallPermissions struct {
	CallPermissions []CallPermissionRelationBase `json:"call_permissions,omitempty"`
}

// NewGroupRelationCallPermissions instantiates a new GroupRelationCallPermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupRelationCallPermissions() *GroupRelationCallPermissions {
	this := GroupRelationCallPermissions{}
	return &this
}

// NewGroupRelationCallPermissionsWithDefaults instantiates a new GroupRelationCallPermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupRelationCallPermissionsWithDefaults() *GroupRelationCallPermissions {
	this := GroupRelationCallPermissions{}
	return &this
}

// GetCallPermissions returns the CallPermissions field value if set, zero value otherwise.
func (o *GroupRelationCallPermissions) GetCallPermissions() []CallPermissionRelationBase {
	if o == nil || IsNil(o.CallPermissions) {
		var ret []CallPermissionRelationBase
		return ret
	}
	return o.CallPermissions
}

// GetCallPermissionsOk returns a tuple with the CallPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRelationCallPermissions) GetCallPermissionsOk() ([]CallPermissionRelationBase, bool) {
	if o == nil || IsNil(o.CallPermissions) {
		return nil, false
	}
	return o.CallPermissions, true
}

// HasCallPermissions returns a boolean if a field has been set.
func (o *GroupRelationCallPermissions) HasCallPermissions() bool {
	if o != nil && !IsNil(o.CallPermissions) {
		return true
	}

	return false
}

// SetCallPermissions gets a reference to the given []CallPermissionRelationBase and assigns it to the CallPermissions field.
func (o *GroupRelationCallPermissions) SetCallPermissions(v []CallPermissionRelationBase) {
	o.CallPermissions = v
}

func (o GroupRelationCallPermissions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupRelationCallPermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CallPermissions) {
		toSerialize["call_permissions"] = o.CallPermissions
	}
	return toSerialize, nil
}

type NullableGroupRelationCallPermissions struct {
	value *GroupRelationCallPermissions
	isSet bool
}

func (v NullableGroupRelationCallPermissions) Get() *GroupRelationCallPermissions {
	return v.value
}

func (v *NullableGroupRelationCallPermissions) Set(val *GroupRelationCallPermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupRelationCallPermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupRelationCallPermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupRelationCallPermissions(val *GroupRelationCallPermissions) *NullableGroupRelationCallPermissions {
	return &NullableGroupRelationCallPermissions{value: val, isSet: true}
}

func (v NullableGroupRelationCallPermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupRelationCallPermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
