/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the AgentRelationSkills type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentRelationSkills{}

// AgentRelationSkills struct for AgentRelationSkills
type AgentRelationSkills struct {
	Skills []AgentRelationSkill `json:"skills,omitempty"`
}

// NewAgentRelationSkills instantiates a new AgentRelationSkills object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentRelationSkills() *AgentRelationSkills {
	this := AgentRelationSkills{}
	return &this
}

// NewAgentRelationSkillsWithDefaults instantiates a new AgentRelationSkills object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentRelationSkillsWithDefaults() *AgentRelationSkills {
	this := AgentRelationSkills{}
	return &this
}

// GetSkills returns the Skills field value if set, zero value otherwise.
func (o *AgentRelationSkills) GetSkills() []AgentRelationSkill {
	if o == nil || IsNil(o.Skills) {
		var ret []AgentRelationSkill
		return ret
	}
	return o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentRelationSkills) GetSkillsOk() ([]AgentRelationSkill, bool) {
	if o == nil || IsNil(o.Skills) {
		return nil, false
	}
	return o.Skills, true
}

// HasSkills returns a boolean if a field has been set.
func (o *AgentRelationSkills) HasSkills() bool {
	if o != nil && !IsNil(o.Skills) {
		return true
	}

	return false
}

// SetSkills gets a reference to the given []AgentRelationSkill and assigns it to the Skills field.
func (o *AgentRelationSkills) SetSkills(v []AgentRelationSkill) {
	o.Skills = v
}

func (o AgentRelationSkills) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentRelationSkills) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Skills) {
		toSerialize["skills"] = o.Skills
	}
	return toSerialize, nil
}

type NullableAgentRelationSkills struct {
	value *AgentRelationSkills
	isSet bool
}

func (v NullableAgentRelationSkills) Get() *AgentRelationSkills {
	return v.value
}

func (v *NullableAgentRelationSkills) Set(val *AgentRelationSkills) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentRelationSkills) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentRelationSkills) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentRelationSkills(val *AgentRelationSkills) *NullableAgentRelationSkills {
	return &NullableAgentRelationSkills{value: val, isSet: true}
}

func (v NullableAgentRelationSkills) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentRelationSkills) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
