/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the ScheduleExceptionalPeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleExceptionalPeriod{}

// ScheduleExceptionalPeriod struct for ScheduleExceptionalPeriod
type ScheduleExceptionalPeriod struct {
	// The end hour of the period. Format <HH:MM>
	HoursEnd *string `json:"hours_end,omitempty"`
	// The start hour of the period. Format <HH:MM>
	HoursStart *string `json:"hours_start,omitempty"`
	// The month days of the period.
	MonthDays []int32 `json:"month_days,omitempty"`
	// The months of the period. Month start with January(1) and end with December(12)
	Months []int32 `json:"months,omitempty"`
	// The week days of the period. Week day start with Monday(1) and end with Sunday(7)
	WeekDays    []int32          `json:"week_days,omitempty"`
	Destination *DestinationType `json:"destination,omitempty"`
}

// NewScheduleExceptionalPeriod instantiates a new ScheduleExceptionalPeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleExceptionalPeriod() *ScheduleExceptionalPeriod {
	this := ScheduleExceptionalPeriod{}
	return &this
}

// NewScheduleExceptionalPeriodWithDefaults instantiates a new ScheduleExceptionalPeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleExceptionalPeriodWithDefaults() *ScheduleExceptionalPeriod {
	this := ScheduleExceptionalPeriod{}
	return &this
}

// GetHoursEnd returns the HoursEnd field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetHoursEnd() string {
	if o == nil || IsNil(o.HoursEnd) {
		var ret string
		return ret
	}
	return *o.HoursEnd
}

// GetHoursEndOk returns a tuple with the HoursEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetHoursEndOk() (*string, bool) {
	if o == nil || IsNil(o.HoursEnd) {
		return nil, false
	}
	return o.HoursEnd, true
}

// HasHoursEnd returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasHoursEnd() bool {
	if o != nil && !IsNil(o.HoursEnd) {
		return true
	}

	return false
}

// SetHoursEnd gets a reference to the given string and assigns it to the HoursEnd field.
func (o *ScheduleExceptionalPeriod) SetHoursEnd(v string) {
	o.HoursEnd = &v
}

// GetHoursStart returns the HoursStart field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetHoursStart() string {
	if o == nil || IsNil(o.HoursStart) {
		var ret string
		return ret
	}
	return *o.HoursStart
}

// GetHoursStartOk returns a tuple with the HoursStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetHoursStartOk() (*string, bool) {
	if o == nil || IsNil(o.HoursStart) {
		return nil, false
	}
	return o.HoursStart, true
}

// HasHoursStart returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasHoursStart() bool {
	if o != nil && !IsNil(o.HoursStart) {
		return true
	}

	return false
}

// SetHoursStart gets a reference to the given string and assigns it to the HoursStart field.
func (o *ScheduleExceptionalPeriod) SetHoursStart(v string) {
	o.HoursStart = &v
}

// GetMonthDays returns the MonthDays field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetMonthDays() []int32 {
	if o == nil || IsNil(o.MonthDays) {
		var ret []int32
		return ret
	}
	return o.MonthDays
}

// GetMonthDaysOk returns a tuple with the MonthDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetMonthDaysOk() ([]int32, bool) {
	if o == nil || IsNil(o.MonthDays) {
		return nil, false
	}
	return o.MonthDays, true
}

// HasMonthDays returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasMonthDays() bool {
	if o != nil && !IsNil(o.MonthDays) {
		return true
	}

	return false
}

// SetMonthDays gets a reference to the given []int32 and assigns it to the MonthDays field.
func (o *ScheduleExceptionalPeriod) SetMonthDays(v []int32) {
	o.MonthDays = v
}

// GetMonths returns the Months field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetMonths() []int32 {
	if o == nil || IsNil(o.Months) {
		var ret []int32
		return ret
	}
	return o.Months
}

// GetMonthsOk returns a tuple with the Months field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetMonthsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Months) {
		return nil, false
	}
	return o.Months, true
}

// HasMonths returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasMonths() bool {
	if o != nil && !IsNil(o.Months) {
		return true
	}

	return false
}

// SetMonths gets a reference to the given []int32 and assigns it to the Months field.
func (o *ScheduleExceptionalPeriod) SetMonths(v []int32) {
	o.Months = v
}

// GetWeekDays returns the WeekDays field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetWeekDays() []int32 {
	if o == nil || IsNil(o.WeekDays) {
		var ret []int32
		return ret
	}
	return o.WeekDays
}

// GetWeekDaysOk returns a tuple with the WeekDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetWeekDaysOk() ([]int32, bool) {
	if o == nil || IsNil(o.WeekDays) {
		return nil, false
	}
	return o.WeekDays, true
}

// HasWeekDays returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasWeekDays() bool {
	if o != nil && !IsNil(o.WeekDays) {
		return true
	}

	return false
}

// SetWeekDays gets a reference to the given []int32 and assigns it to the WeekDays field.
func (o *ScheduleExceptionalPeriod) SetWeekDays(v []int32) {
	o.WeekDays = v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *ScheduleExceptionalPeriod) GetDestination() DestinationType {
	if o == nil || IsNil(o.Destination) {
		var ret DestinationType
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduleExceptionalPeriod) GetDestinationOk() (*DestinationType, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *ScheduleExceptionalPeriod) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given DestinationType and assigns it to the Destination field.
func (o *ScheduleExceptionalPeriod) SetDestination(v DestinationType) {
	o.Destination = &v
}

func (o ScheduleExceptionalPeriod) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleExceptionalPeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HoursEnd) {
		toSerialize["hours_end"] = o.HoursEnd
	}
	if !IsNil(o.HoursStart) {
		toSerialize["hours_start"] = o.HoursStart
	}
	if !IsNil(o.MonthDays) {
		toSerialize["month_days"] = o.MonthDays
	}
	if !IsNil(o.Months) {
		toSerialize["months"] = o.Months
	}
	if !IsNil(o.WeekDays) {
		toSerialize["week_days"] = o.WeekDays
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	return toSerialize, nil
}

type NullableScheduleExceptionalPeriod struct {
	value *ScheduleExceptionalPeriod
	isSet bool
}

func (v NullableScheduleExceptionalPeriod) Get() *ScheduleExceptionalPeriod {
	return v.value
}

func (v *NullableScheduleExceptionalPeriod) Set(val *ScheduleExceptionalPeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleExceptionalPeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleExceptionalPeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleExceptionalPeriod(val *ScheduleExceptionalPeriod) *NullableScheduleExceptionalPeriod {
	return &NullableScheduleExceptionalPeriod{value: val, isSet: true}
}

func (v NullableScheduleExceptionalPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleExceptionalPeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
