/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the SwitchboardRelationBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SwitchboardRelationBase{}

// SwitchboardRelationBase struct for SwitchboardRelationBase
type SwitchboardRelationBase struct {
	// Switchboard name
	Name *string `json:"name,omitempty"`
	// Switchboard UUID
	Uuid *string `json:"uuid,omitempty"`
}

// NewSwitchboardRelationBase instantiates a new SwitchboardRelationBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwitchboardRelationBase() *SwitchboardRelationBase {
	this := SwitchboardRelationBase{}
	return &this
}

// NewSwitchboardRelationBaseWithDefaults instantiates a new SwitchboardRelationBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwitchboardRelationBaseWithDefaults() *SwitchboardRelationBase {
	this := SwitchboardRelationBase{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SwitchboardRelationBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchboardRelationBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SwitchboardRelationBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SwitchboardRelationBase) SetName(v string) {
	o.Name = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *SwitchboardRelationBase) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SwitchboardRelationBase) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *SwitchboardRelationBase) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *SwitchboardRelationBase) SetUuid(v string) {
	o.Uuid = &v
}

func (o SwitchboardRelationBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SwitchboardRelationBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullableSwitchboardRelationBase struct {
	value *SwitchboardRelationBase
	isSet bool
}

func (v NullableSwitchboardRelationBase) Get() *SwitchboardRelationBase {
	return v.value
}

func (v *NullableSwitchboardRelationBase) Set(val *SwitchboardRelationBase) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchboardRelationBase) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchboardRelationBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchboardRelationBase(val *SwitchboardRelationBase) *NullableSwitchboardRelationBase {
	return &NullableSwitchboardRelationBase{value: val, isSet: true}
}

func (v NullableSwitchboardRelationBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchboardRelationBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
