/*
accent-confd

Confd exposes an API for managing core resources on a Accent server such as users, extensions, devices, voicemails, queues, etc. Resources can be associated together to provide additional functionality. For example: By associating a voicemail with a user, calls will automatically fallback on to the voicemail when the user cannot answer.  Implementation notes ====================  Errors ------  Responses containing errors will have a status code in the 400 or 500 class. A list of error messages will be returned in the body of the response as a JSON-encoded array:  ~~~ [     \"Input error - User not found\",     \"Resource error - User not associated to a line\" ] ~~~   Updating resources via PUT --------------------------  When updating a resource, all fields become optional. In other words, only values that have been changed need to be sent to the server. Please note that this behavior may change in future versions of the API.

API version: 1.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package confd

import (
	"encoding/json"
)

// checks if the WizardDiscoverGateway type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WizardDiscoverGateway{}

// WizardDiscoverGateway struct for WizardDiscoverGateway
type WizardDiscoverGateway struct {
	// Gateway IPv4 address
	Gateway *string `json:"gateway,omitempty"`
	// Interface name (e.g. eth0)
	Interface *string `json:"interface,omitempty"`
}

// NewWizardDiscoverGateway instantiates a new WizardDiscoverGateway object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWizardDiscoverGateway() *WizardDiscoverGateway {
	this := WizardDiscoverGateway{}
	return &this
}

// NewWizardDiscoverGatewayWithDefaults instantiates a new WizardDiscoverGateway object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWizardDiscoverGatewayWithDefaults() *WizardDiscoverGateway {
	this := WizardDiscoverGateway{}
	return &this
}

// GetGateway returns the Gateway field value if set, zero value otherwise.
func (o *WizardDiscoverGateway) GetGateway() string {
	if o == nil || IsNil(o.Gateway) {
		var ret string
		return ret
	}
	return *o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WizardDiscoverGateway) GetGatewayOk() (*string, bool) {
	if o == nil || IsNil(o.Gateway) {
		return nil, false
	}
	return o.Gateway, true
}

// HasGateway returns a boolean if a field has been set.
func (o *WizardDiscoverGateway) HasGateway() bool {
	if o != nil && !IsNil(o.Gateway) {
		return true
	}

	return false
}

// SetGateway gets a reference to the given string and assigns it to the Gateway field.
func (o *WizardDiscoverGateway) SetGateway(v string) {
	o.Gateway = &v
}

// GetInterface returns the Interface field value if set, zero value otherwise.
func (o *WizardDiscoverGateway) GetInterface() string {
	if o == nil || IsNil(o.Interface) {
		var ret string
		return ret
	}
	return *o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WizardDiscoverGateway) GetInterfaceOk() (*string, bool) {
	if o == nil || IsNil(o.Interface) {
		return nil, false
	}
	return o.Interface, true
}

// HasInterface returns a boolean if a field has been set.
func (o *WizardDiscoverGateway) HasInterface() bool {
	if o != nil && !IsNil(o.Interface) {
		return true
	}

	return false
}

// SetInterface gets a reference to the given string and assigns it to the Interface field.
func (o *WizardDiscoverGateway) SetInterface(v string) {
	o.Interface = &v
}

func (o WizardDiscoverGateway) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WizardDiscoverGateway) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Gateway) {
		toSerialize["gateway"] = o.Gateway
	}
	if !IsNil(o.Interface) {
		toSerialize["interface"] = o.Interface
	}
	return toSerialize, nil
}

type NullableWizardDiscoverGateway struct {
	value *WizardDiscoverGateway
	isSet bool
}

func (v NullableWizardDiscoverGateway) Get() *WizardDiscoverGateway {
	return v.value
}

func (v *NullableWizardDiscoverGateway) Set(val *WizardDiscoverGateway) {
	v.value = val
	v.isSet = true
}

func (v NullableWizardDiscoverGateway) IsSet() bool {
	return v.isSet
}

func (v *NullableWizardDiscoverGateway) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWizardDiscoverGateway(val *WizardDiscoverGateway) *NullableWizardDiscoverGateway {
	return &NullableWizardDiscoverGateway{value: val, isSet: true}
}

func (v NullableWizardDiscoverGateway) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWizardDiscoverGateway) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
