host: api.accentvoice.io
basePath: /1.0
definitions:
  ComponentWithStatus:
    properties:
      status:
        $ref: '#/definitions/StatusValue'
    type: object
  Error:
    description: Error message for the client
    properties:
      details:
        description: Additional information about the error. The keys are specific
          to each error.
        type: object
      error_id:
        description: Identifier of the type of error. It is more precise than the
          HTTP status code.
        type: string
      message:
        description: Human readable explanation of the error
        type: string
      timestamp:
        description: Time when the error occured
        format: timestamp
        type: number
    title: Error
  SetupRequest:
    properties:
      engine_instance_uuid:
        description: 'The UUID identifying this instance on Nestbox.
          The engine_instance_uuid should only be specified if the instance has already
          been registered on the specified Nestbox. Omitting this field for an instance
          that is already registered will create a duplicate entry on the Nestbox.
          '
        type: string
      engine_internal_address:
        description: IP address of the engine
        type: string
      engine_language:
        description: The interface language for the Accent Engine (either `en_US` or
          `fr_FR`)
        type: string
      engine_license:
        description: Whether the GNU GPLv3 license is accepted
        type: boolean
      engine_password:
        description: Password of the first administrator ``root`` on the engine
        type: string
      engine_rtp_icesupport:
        default: false
        description: 'Enable ICE support. This is required for WebRTC.
          A STUN server must be defined in the `engine_rtp_stunaddr` field when using
          `engine_rtp_icesupport=true`.
          '
        type: boolean
      engine_rtp_stunaddr:
        default: 'null'
        description: The address of the STUN server to use for WebRTC
        type: string
      nestbox_engine_host:
        description: Host used by Nestbox to contact the engine
        type: string
      nestbox_engine_port:
        default: 443
        description: Port used by Nestbox to contact the engine
        type: integer
      nestbox_host:
        description: Host of the Nestbox where the engine will register. Specifying
          this key will make nestbox and `engine_internal_address` keys mandatory.
          Accent will be connected to the specified Nestbox instance.
        type: string
      nestbox_instance_name:
        description: Name of the engine in Nestbox
        type: string
      nestbox_port:
        default: 443
        description: Port of the Nestbox where the engine will register
        type: integer
      nestbox_service_id:
        description: Nestbox username used to register the engine
        type: string
      nestbox_service_key:
        description: Nestbox password used to register the engine
        type: string
      nestbox_verify_certificate:
        default: true
        description: Should the certificate used for HTTPS be verified? The setup
          will abort if the certificate fails the verification.
        type: boolean
    required:
    - engine_language
    - engine_password
    - engine_license
    type: object
  StatusSummary:
    properties:
      master_tenant:
        $ref: '#/definitions/ComponentWithStatus'
      rest_api:
        $ref: '#/definitions/ComponentWithStatus'
    type: object
  StatusValue:
    enum:
    - fail
    - ok
    type: string
info:
  contact:
    email: help@accentvoice.io
    name: Accent Team
    url: https://accentvoice.io/
  description: Initialize Accent Engine from a REST API
  title: accent-setupd
  version: 1.0.0
  x-logo:
    altText: Accent Logo
    backgroundColor: '#FAFAFA'
    url: https://accentvoice.io/images/logo-black.svg
parameters:
  SetupBody:
    description: Setup options
    in: body
    name: body
    required: true
    schema:
      $ref: '#/definitions/SetupRequest'
  TokenID:
    description: The token's ID
    in: query
    name: token
    type: string
paths:
  /config:
    get:
      description: '**Required ACL:** `setupd.config.read`'
      operationId: getConfig
      produces:
      - application/json
      responses:
        '200':
          description: The configuration of the service
      summary: Show the current configuration
      tags:
      - config
  /setup:
    post:
      operationId: create
      parameters:
      - $ref: '#/parameters/SetupBody'
      responses:
        '201':
          description: The setup has been completed
        '400':
          $ref: '#/responses/InvalidRequest'
        '500':
          $ref: '#/responses/SetupError'
        '503':
          $ref: '#/responses/AnotherServiceUnavailable'
      summary: Setup the Accent Engine
      tags:
      - setup
  /status:
    get:
      description: '**Required ACL:** `setupd.status.read`'
      operationId: getStatus
      responses:
        '200':
          description: The internal infos of accent-setupd
          schema:
            $ref: '#/definitions/StatusSummary'
      summary: Print infos about internal status of accent-setupd
      tags:
      - status
produces:
- application/json
responses:
  AnotherServiceUnavailable:
    description: Another service is unavailable (e.g. accent-auth, accent-confd, Asterisk,
      ...)
    schema:
      $ref: '#/definitions/Error'
  InvalidRequest:
    description: Invalid request
    schema:
      $ref: '#/definitions/Error'
  NotFoundError:
    description: The resource requested was not found on the server
    schema:
      $ref: '#/definitions/Error'
  SetupError:
    description: A error occurred during the setup
    schema:
      $ref: '#/definitions/Error'
schemes:
- http
- https
security:
- accent_auth_token: []
securityDefinitions:
  accent_auth_token:
    in: header
    name: X-Auth-Token
    type: apiKey
swagger: '2.0'
x-accent-name: setupd
x-accent-port: 9302
