/*
accent-agentd

Testing AgentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentd

import (
	"context"
	openapiclient "github.com/ryanwclark1/accent-ui2/internal/client/agentd"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_agentd_AgentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AgentsAPIService GetAgents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.AgentsAPI.GetAgents(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentsAPIService LogoffAgents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.AgentsAPI.LogoffAgents(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AgentsAPIService RelogAgents", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.AgentsAPI.RelogAgents(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
