/*
accent-calld

Testing SwitchboardsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package calld

import (
	"context"
	openapiclient "github.com/ryanwclark/accent-voice/calld"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_calld_SwitchboardsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SwitchboardsAPIService AnswerHeldCall", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var switchboardUuid string
		var callId string

		resp, httpRes, err := apiClient.SwitchboardsAPI.AnswerHeldCall(context.Background(), switchboardUuid, callId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SwitchboardsAPIService AnswerQueuedCall", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var switchboardUuid string
		var callId string

		resp, httpRes, err := apiClient.SwitchboardsAPI.AnswerQueuedCall(context.Background(), switchboardUuid, callId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SwitchboardsAPIService HoldSwitchboardCall", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var switchboardUuid string
		var callId string

		httpRes, err := apiClient.SwitchboardsAPI.HoldSwitchboardCall(context.Background(), switchboardUuid, callId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SwitchboardsAPIService ListSwitchboardHeldCalls", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var switchboardUuid string

		resp, httpRes, err := apiClient.SwitchboardsAPI.ListSwitchboardHeldCalls(context.Background(), switchboardUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SwitchboardsAPIService ListSwitchboardQueuedCalls", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var switchboardUuid string

		resp, httpRes, err := apiClient.SwitchboardsAPI.ListSwitchboardQueuedCalls(context.Background(), switchboardUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
