/*
accent-plugind

Accent's plugin management service

API version: 0.2
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plugind

import (
	"encoding/json"
)

// checks if the InstallResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallResponse{}

// InstallResponse struct for InstallResponse
type InstallResponse struct {
	// A UUID associated to this plugin installation
	Uuid *string `json:"uuid,omitempty"`
}

// NewInstallResponse instantiates a new InstallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallResponse() *InstallResponse {
	this := InstallResponse{}
	return &this
}

// NewInstallResponseWithDefaults instantiates a new InstallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallResponseWithDefaults() *InstallResponse {
	this := InstallResponse{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *InstallResponse) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstallResponse) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *InstallResponse) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *InstallResponse) SetUuid(v string) {
	o.Uuid = &v
}

func (o InstallResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	return toSerialize, nil
}

type NullableInstallResponse struct {
	value *InstallResponse
	isSet bool
}

func (v NullableInstallResponse) Get() *InstallResponse {
	return v.value
}

func (v *NullableInstallResponse) Set(val *InstallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallResponse(val *InstallResponse) *NullableInstallResponse {
	return &NullableInstallResponse{value: val, isSet: true}
}

func (v NullableInstallResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
